version: "3"

networks:
  loki:


x-logging:
  &logging
  driver: "json-file"
  options:
    max-size: "200m"
    max-file: "10"
    tag: "{{.ImageName}}|{{.Name}}"

services:
  app_python:
    image: lexasmall/lab2app:latest
    ports:
      - "5000:5000"
    networks:
      - loki
    logging: *logging

  loki:
    image: grafana/loki:2.6.1
    ports:
      - "3100:3100"
    networks:
      - loki
    logging: *logging

  promtail:
    image: grafana/promtail:2.6.1
    command:
      - "--config.file=/etc/promtail-config.yml"
    networks:
      - loki
    logging: *logging

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
    logging: *logging
  
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: monitoring.prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    healthcheck:
      test: wget --no-verbose --spider http://localhost:9090/-/healthy || exit 1
      interval: 10s
      timeout: 2s
      retries: 3